services:
  redis:
    image: redis:7.4.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  app:
    build: .
    restart: always
    environment:
      PREDEFINED_HASH: ${PREDEFINED_HASH}
      URL_PREFIX: ${URL_PREFIX}
    ports:
      - "${HOST_IP:-127.0.0.1}:11211:8000"
    volumes:
      - ./secrets:/app/secrets
    depends_on:
      redis:
        condition: service_healthy
